# Generated by Django 6.0.5 on 2026-05-13 16:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal_type', models.CharField(choices=[('accumulation', 'Acumulação'), ('reduction', 'Redução')], max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='goals', to='accounts.financialaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='categories.category')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
            },
        ),
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('on_track', 'No caminho'), ('at_risk', 'Em risco'), ('achieved', 'Atingido'), ('missed', 'Não atingida')], default='on_track', max_length=20)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_goals', to='goals.goal')),
            ],
            options={
                'verbose_name': 'Meta Mensal',
                'verbose_name_plural': 'Metas Mensais',
                'unique_together': {('goal', 'year', 'month')},
            },
        ),
    ]
