# Generated by Codex on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0002_cardstatement"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="Descricao")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Valor total",
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Valor da parcela",
                    ),
                ),
                (
                    "total_installments",
                    models.PositiveIntegerField(verbose_name="Total de parcelas"),
                ),
                (
                    "first_installment_date",
                    models.DateField(verbose_name="Data da primeira parcela"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("completed", "Concluido"),
                            ("canceled", "Cancelado"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plans",
                        to="cards.card",
                        verbose_name="Cartao",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installment_plans",
                        to="categories.category",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcelamento",
                "verbose_name_plural": "Parcelamentos",
                "ordering": ["status", "first_installment_date", "description"],
            },
        ),
    ]
