# Generated by Django 6.0.5 on 2026-05-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_options_alter_cardstatement_options_and_more'),
        ('installments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='cards.card', verbose_name='Cartão'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
