# Generated by Django 6.0.5 on 2026-05-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('transactions', '0002_transaction_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('csv', 'CSV'), ('ofx', 'OFX'), ('xlsx', 'XLSX')], max_length=20)),
                ('raw_description', models.CharField(max_length=255)),
                ('normalized_description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('suggested_transaction_type', models.CharField(blank=True, choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('discarded', 'Descartada'), ('duplicate', 'Duplicada')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('import_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
                ('suggested_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.financialaccount')),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
            ],
            options={
                'verbose_name': 'Transação Importada',
                'verbose_name_plural': 'Transações Importadas',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'date'], name='imports_imp_status_c22e0c_idx'), models.Index(fields=['source_type', 'source_file_name'], name='imports_imp_source__4d8139_idx')],
            },
        ),
    ]
