# Generated by Django 6.0.5 on 2026-06-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedtransaction',
            name='review_error',
            field=models.TextField(blank=True),
        ),
    ]
