# Generated by Django 6.0.5 on 2026-05-15 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('goals', '0001_initial'),
        ('recurrences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_key', models.CharField(max_length=120, unique=True)),
                ('reason', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Padrão Ignorado',
                'verbose_name_plural': 'Padrões Ignorados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('insight_type', models.CharField(choices=[('recurring_expense', 'Despesa Recorrente'), ('category_limit', 'Limite de Categoria'), ('monthly_goal', 'Meta Mensal'), ('bill_reminder', 'Lembrete de Conta'), ('low_balance', 'Saldo Baixo')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('ignored', 'Ignorado'), ('silenced', 'Silenciado')], default='pending', max_length=20)),
                ('suggested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('monthly_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.monthlygoal')),
                ('recurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recurrences.recurrence')),
            ],
            options={
                'verbose_name': 'Insight',
                'verbose_name_plural': 'Insights',
                'ordering': ['-title', '-created_at'],
            },
        ),
    ]
