# Generated by Django 6.0.5 on 2026-05-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insight',
            old_name='source',
            new_name='source_key',
        ),
    ]
