# Generated by Django 6.0.5 on 2026-05-07 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('account_type', models.CharField(choices=[('checking', 'Conta corrente'), ('savings', 'Poupanca'), ('piggy_bank', 'Porquinho'), ('benefit', 'Beneficio'), ('global', 'Conta global'), ('cash', 'Dinheiro'), ('investment', 'Investimento')], max_length=20, verbose_name='Tipo')),
                ('currency', models.CharField(choices=[('BRL', 'Real brasileiro'), ('USD', 'Dolar americano')], default='BRL', max_length=3, verbose_name='Moeda')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo atual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='institutions.institution', verbose_name='Instituicao')),
            ],
            options={
                'verbose_name': 'Conta financeira',
                'verbose_name_plural': 'Contas financeiras',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'name'), name='unique_account_name_per_institution')],
            },
        ),
    ]
