# Generated by Django 6.0.5 on 2026-05-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('institutions', '0002_alter_institution_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccount',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Conta corrente'), ('savings', 'Poupança'), ('piggy_bank', 'Porquinho'), ('benefit', 'Benefício'), ('global', 'Conta global'), ('cash', 'Dinheiro'), ('investment', 'Investimento')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='currency',
            field=models.CharField(choices=[('BRL', 'Real brasileiro'), ('USD', 'Dólar americano')], default='BRL', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='institutions.institution', verbose_name='Instituição'),
        ),
    ]
