# Generated by Django 6.0.5 on 2026-05-12 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cards', '0002_cardstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expected_day', models.PositiveIntegerField()),
                ('frequency', models.CharField(choices=[('monthly', 'Mensal'), ('annual', 'Anual'), ('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('quarterly', 'Trimestral'), ('custom', 'Personalizada')], max_length=20)),
                ('recurrence_type', models.CharField(choices=[('income', 'Receita'), ('fixed_bill', 'Despesa fixa'), ('subscription', 'Assinatura'), ('other', 'Outro')], max_length=20)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_confirmation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='accounts.financialaccount', verbose_name='Conta financeira')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='cards.card', verbose_name='Cartão de crédito')),
            ],
            options={
                'verbose_name': 'Recorrência',
                'verbose_name_plural': 'Recorrências',
                'ordering': ['expected_day', 'name', 'recurrence_type'],
            },
        ),
    ]
