# Generated by Django 6.0.5 on 2026-05-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountYieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_type', models.CharField(choices=[('none', 'Sem rendimento'), ('cdi_percentage', '% do CDI')], max_length=30, verbose_name='Tipo de rendimento')),
                ('cdi_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Percentual do CDI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yield_config', to='accounts.financialaccount', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Configuracao de rendimento',
                'verbose_name_plural': 'Configuracoes de rendimento',
                'ordering': ['account__name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('cdi', 'CDI')], max_length=20, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Data')),
                ('value', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Valor')),
                ('periodicity', models.CharField(choices=[('annual', 'Anual')], default='annual', max_length=20, verbose_name='Periodicidade')),
                ('source', models.CharField(default='manual', max_length=80, verbose_name='Fonte')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Taxa de referencia',
                'verbose_name_plural': 'Taxas de referencia',
                'ordering': ['-date', 'rate_type'],
                'constraints': [models.UniqueConstraint(fields=('rate_type', 'date', 'periodicity'), name='unique_reference_rate_per_type_date_periodicity')],
            },
        ),
    ]
