# Generated by Django 6.0.5 on 2026-05-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountyieldconfig',
            options={'ordering': ['account__name'], 'verbose_name': 'Configuração de rendimento', 'verbose_name_plural': 'Configurações de rendimento'},
        ),
        migrations.AlterModelOptions(
            name='referencerate',
            options={'ordering': ['-date', 'rate_type'], 'verbose_name': 'Taxa de referência', 'verbose_name_plural': 'Taxas de referência'},
        ),
        migrations.AlterField(
            model_name='referencerate',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
