# Generated by Django 6.0.5 on 2026-05-08 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cards', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descricao')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('transaction_type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('adjustment', 'Ajuste'), ('card_purchase', 'Compra no cartao'), ('forecast', 'Previsao'), ('statement_payment', 'Pagamento de fatura')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('forecasted', 'Previsto'), ('pending', 'Pendente'), ('paid', 'Pago'), ('partially_paid', 'Pago parcial'), ('late', 'Atrasado'), ('canceled', 'Cancelado'), ('ignored', 'Ignorado')], default='pending', max_length=20, verbose_name='Status')),
                ('date', models.DateField(verbose_name='Data da transacao')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.financialaccount', verbose_name='Conta financeira')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cards.card', verbose_name='Cartao de credito')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Transacao',
                'verbose_name_plural': 'Transacoes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descricao')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data da transferencia')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='accounts.financialaccount', verbose_name='Conta de destino')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='accounts.financialaccount', verbose_name='Conta de origem')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
