# Generated by Codex on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installments", "0001_initial"),
        ("transactions", "0002_transaction_statement"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="installment_number",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Numero da parcela",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="installment_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="installments.installmentplan",
                verbose_name="Plano de parcelamento",
            ),
        ),
    ]
