# Generated by Django 6.0.5 on 2026-05-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_options_alter_cardstatement_options_and_more'),
        ('transactions', '0003_transaction_installment_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Transferência', 'verbose_name_plural': 'Transferências'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cards.card', verbose_name='Cartão de crédito'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Data da transação'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número da parcela'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('adjustment', 'Ajuste'), ('card_purchase', 'Compra no cartão'), ('forecast', 'Previsão'), ('statement_payment', 'Pagamento de fatura')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(verbose_name='Data da transferência'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
