# Generated by Django 6.0.5 on 2026-06-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_options_alter_transfer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('adjustment', 'Ajuste'), ('card_purchase', 'Compra no cartão'), ('benefit_purchase', 'Compra no benefício'), ('forecast', 'Previsão'), ('statement_payment', 'Pagamento de fatura')], max_length=20, verbose_name='Tipo'),
        ),
    ]
