# Generated by Django 6.0.5 on 2026-07-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('slate', 'Cinza'), ('red', 'Vermelho'), ('green', 'Verde'), ('blue', 'Azul'), ('yellow', 'Amarelo')], max_length=50, null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('home', 'Casa'), ('card', 'Cartão'), ('dollar', 'Dinheiro'), ('tag', 'Etiqueta'), ('chart', 'Gráfico')], max_length=50, null=True, verbose_name='Ícone'),
        ),
    ]
