# Generated by Django 6.0.5 on 2026-05-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('card_type', models.CharField(choices=[('credit', 'Credito'), ('benefit', 'Beneficio'), ('transport', 'Transporte'), ('prepaid', 'Pre-pago')], max_length=20, verbose_name='Tipo')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Limite')),
                ('statement_closing_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dia de fechamento')),
                ('statement_due_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dia de vencimento')),
                ('estimated_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Saldo estimado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='institutions.institution', verbose_name='Instituicao')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards_as_payment_account', to='accounts.financialaccount', verbose_name='Conta padrao de pagamento')),
            ],
            options={
                'verbose_name': 'Cartao',
                'verbose_name_plural': 'Cartoes',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'name'), name='unique_card_name_per_institution')],
            },
        ),
    ]
