# Generated by Django 6.0.5 on 2026-05-11 16:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('closed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor fechado')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor esperado')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor pago')),
                ('closing_date', models.DateField(verbose_name='Data de fechamento')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('status', models.CharField(choices=[('forecasted', 'Previsao'), ('late', 'Atrasada'), ('open', 'Aberta'), ('pending', 'Pendente'), ('paid', 'Paga'), ('canceled', 'Cancelada'), ('partially_paid', 'Parcialmente paga')], default='open', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='cards.card', verbose_name='Cartao')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_statements_as_payment_account', to='accounts.financialaccount', verbose_name='Conta de pagamento')),
            ],
            options={
                'verbose_name': 'Fatura do cartao',
                'verbose_name_plural': 'Faturas do cartao',
                'ordering': ['-year', '-month', 'card'],
                'constraints': [models.UniqueConstraint(fields=('card', 'year', 'month'), name='unique_card_statement_per_month')],
            },
        ),
    ]
