# Generated by Django 6.0.5 on 2026-05-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_financialaccount_account_type_and_more'),
        ('cards', '0002_cardstatement'),
        ('institutions', '0002_alter_institution_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['name'], 'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AlterModelOptions(
            name='cardstatement',
            options={'ordering': ['-year', '-month', 'card'], 'verbose_name': 'Fatura do cartão', 'verbose_name_plural': 'Faturas do cartão'},
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('credit', 'Crédito'), ('benefit', 'Benefício'), ('transport', 'Transporte'), ('prepaid', 'Pré-pago')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='card',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='institutions.institution', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='card',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards_as_payment_account', to='accounts.financialaccount', verbose_name='Conta padrão de pagamento'),
        ),
        migrations.AlterField(
            model_name='cardstatement',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='cards.card', verbose_name='Cartão'),
        ),
        migrations.AlterField(
            model_name='cardstatement',
            name='month',
            field=models.PositiveSmallIntegerField(verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='cardstatement',
            name='status',
            field=models.CharField(choices=[('forecasted', 'Previsão'), ('late', 'Atrasada'), ('open', 'Aberta'), ('pending', 'Pendente'), ('paid', 'Paga'), ('canceled', 'Cancelada'), ('partially_paid', 'Parcialmente paga')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
